// Code generated by "stringer -type=SuitType"; DO NOT EDIT.

package deck

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Spade-0]
	_ = x[Diamond-1]
	_ = x[Club-2]
	_ = x[Heart-3]
	_ = x[Joker-4]
}

const _SuitType_name = "SpadeDiamondClubHeartJoker"

var _SuitType_index = [...]uint8{0, 5, 12, 16, 21, 26}

func (i SuitType) String() string {
	if i < 0 || i >= SuitType(len(_SuitType_index)-1) {
		return "SuitType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _SuitType_name[_SuitType_index[i]:_SuitType_index[i+1]]
}
