// Code generated by "stringer -type=SuitValue"; DO NOT EDIT.

package deck

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Ace-0]
	_ = x[Two-1]
	_ = x[Three-2]
	_ = x[Four-3]
	_ = x[Five-4]
	_ = x[Six-5]
	_ = x[Seven-6]
	_ = x[Eight-7]
	_ = x[Nine-8]
	_ = x[Ten-9]
	_ = x[Jack-10]
	_ = x[Queen-11]
	_ = x[King-12]
}

const _SuitValue_name = "AceTwoThreeFourFiveSixSevenEightNineTenJackQueenKing"

var _SuitValue_index = [...]uint8{0, 3, 6, 11, 15, 19, 22, 27, 32, 36, 39, 43, 48, 52}

func (i SuitValue) String() string {
	if i < 0 || i >= SuitValue(len(_SuitValue_index)-1) {
		return "SuitValue(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _SuitValue_name[_SuitValue_index[i]:_SuitValue_index[i+1]]
}
